architect:
- yegor256
- dmarkov
install: |-
  sudo gem install pdd
  sudo apt-get install -y fontforge
  wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  unzip woff-code-latest.zip -d sfnt2woff
  cd sfnt2woff
  make
  sudo mv sfnt2woff /usr/local/bin/
  cd ..
  sudo gem install fontcustom
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - caarlos0
  - carlosmiranda
  - darkled
  - dmzaytsev
  - ggajos
  - hdouss
  - krzyk
  - longtimeago
  - mkordas
  - pinaf
deploy:
  script: |-
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=jcabi-maven-skin.xml
    s3cmd --no-progress put jcabi-maven-skin.xml --config=../s3cfg s3://pdd.teamed.io/jcabi-maven-skin.xml
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml || echo 'site-deploy failed'
  commanders:
  - yegor256