language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - unset GEM_PATH
install: |
  apt-get install fontforge
  wget http://people.mozilla.com/~jkew/woff/woff-code-latest.zip
  unzip woff-code-latest.zip -d sfnt2woff
  cd sfnt2woff
  make
  mv sfnt2woff /usr/local/bin/
  cd ..
  gem install fontcustom
script: |
  mvn clean install -Pqulice
